[package]
name = "keywords"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
regex = "1.10.3"
scraper = "0.18.1"
