version: '3.8'
services:
  rust-api:
    container_name: rust-api
    build:
      context: .
      dockerfile: apps/rust-api/Dockerfile
    ports:
      - "8000:8000"
  next-app:
    container_name: next-js
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_RUST_API_URL=http://rust-api:8000
  postgres:
    container_name: postgresCont
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: whatever
      POSTGRES_DB: keywords_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: