

pub fn keyword_input() -> Vec<(&'static str, Vec<&'static str>)> {
     return vec![
          ("typescript", vec!["typescript"]),
          ("javascript", vec!["javascript"]),
          ("react", vec!["react", "react.js"]),
          ("next.js", vec!["next.js", "nextjs"]),
          ("node.js", vec!["node.js", "node"]),
          ("rust", vec!["rust"]),
          ("express.js", vec!["express.js", "express"]),
          ("html", vec!["html", "html5"]),
          ("css", vec!["css", "css3"]),
          ("docker", vec!["docker"]),
          ("mysql", vec!["mysql", "sql"]),
          ("mongodb", vec!["mongodb"]),
          ("prisma", vec!["prisma"]),
          ("laravel", vec!["laravel"]),
          ("php", vec!["php"]),
          ("google cloud platform", vec!["google cloud platform", "gcp"]),
          ("webpack", vec!["webpack"]),
          ("git", vec!["git"]),
          ("github", vec!["github", "git hub"]),
          ("python", vec!["python"]),
          ("redux", vec!["redux"]),
          ("jest", vec!["jest"]),
          ("styled components", vec!["styled components", "styled-components"]),
          ("firebase", vec!["firebase"]),
          ("burp suite", vec!["burp suite", "burpsuite"]),
          ("cybersecurity", vec!["cybersecurity", "cyber security", "cyber-security"]),
          ("pug", vec!["pug"]),
          ("front-end", vec!["front-end", "frontend", "front end", "frontend development"]),
          ("back-end", vec!["back-end", "backend", "back end", "backend development"]),
          ("full stack", vec!["full stack", "fullstack", "full-stack", "fullstack development"]),
          ("web development", vec!["web development", "web dev"]),
          ("ecmascript", vec!["ecmascript", "es6", "es7", "es8", "es9", "es10", "es11", "es12", "es13", "es14", "es15", "es16", "es17", "es18", "es19", "es20", "esNext"]),
          ("shell", vec!["shell"]),
          ("bash", vec!["bash"]),
          ("cli", vec!["cli", "command line interface"]),
          ("redis", vec!["redis"]),
          ("jira", vec!["jira"]),
          ("confluence", vec!["confluence"]),
          ("agile", vec!["agile"]),
          ("scrum", vec!["scrum"]),
          ("slack", vec!["slack"]),
          ("zoom", vec!["zoom"]),
          ("atlassian", vec!["atlassian"]),
          ("ci/cd", vec!["ci/cd", "ci cd", "continuous integration", "continuous deployment"]),
          ("devops", vec!["devops", "dev ops"]),
          ("nginx", vec!["nginx"]),
          ("apache", vec!["apache"]),
          ("http", vec!["http"]),
          ("https", vec!["https"]),
          ("linux", vec!["linux"]),
          ("api", vec!["api"]),
          ("cms", vec!["cms", "content management system"]),
          ("wcag", vec!["wcag", "web content accessibility guidelines"]),
          ("accessibility", vec!["accessibility"]),
          ("architecture", vec!["architecture"]),
          ("design", vec!["design"]),
          ("ui", vec!["ui", "user interface"]),
          ("ux", vec!["ux", "user experience"]),
          ("testing", vec!["testing"]),
          ("automation", vec!["automation"]),
     ];
}